export { default as LandingPage } from "./LandingPage";
export { default as Footer } from "./footer";
export { default as App } from "./app";
export { default as Contact } from "./Contact";
export { default as DespreNoi } from "./DespreNoi";
export { default as Proiecte } from "./Proiecte";
export { default as Servicii } from "./Servicii";
export { default as Sustine } from "./Sustine";
export { default as Login} from "./login";
export {default as Register} from "./Register";