const SET_LANGUAGE = "session/SET_LANGUAGE";
const DISPLAY_REGISTER_POPUP = "session/DISPLAY_REGISTER_POPUP";
const DISPLAY_LOGIN_POPUP = "session/DISPLAY_LOGIN_POPUP";

const REGISTER_USER = "session/REGISTER_USER";
const REGISTER_USER_COMPLETED = "session/REGISTER_USER_COMPLETED";
const REGISTER_USER_FAILED = "session/REGISTER_USER_FAILED";

const LOGIN_USER = "session/LOGIN_USER";
const LOGIN_USER_COMPLETED = "session/LOGIN_USER_COMPLETED";
const LOGIN_USER_FAILED = "session/LOGIN_USER_FAILED";

const SET_USERNAME = "session/SET_USERNAME";

export default {
    SET_LANGUAGE,
    DISPLAY_LOGIN_POPUP,
    DISPLAY_REGISTER_POPUP,
    REGISTER_USER,
    REGISTER_USER_COMPLETED,
    REGISTER_USER_FAILED,
    LOGIN_USER,
    LOGIN_USER_COMPLETED,
    LOGIN_USER_FAILED,
    SET_USERNAME,
};
