const SET_LANGUAGE = "session/SET_LANGUAGE";
const DISPLAY_REGISTER_POPUP = "session/DISPLAY_REGISTER_POPUP";
const DISPLAY_LOGIN_POPUP = "session/DISPLAY_LOGIN_POPUP";

export default {
    SET_LANGUAGE,
    DISPLAY_LOGIN_POPUP,
    DISPLAY_REGISTER_POPUP
};
